create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  birth_date date,
  notes text,
  profile_photo text,
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.procedures (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12,2) not null default 0,
  duration integer not null default 30,
  cover_photo text,
  attachments jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  procedure_id bigint not null references public.procedures(id) on delete cascade,
  appointment_date date not null,
  appointment_time time not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'cancelled')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  category text,
  amount numeric(12,2) not null check (amount > 0),
  expense_date date not null,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_appointments_date_time on public.appointments(appointment_date, appointment_time);
create index if not exists idx_appointments_status on public.appointments(status);
create index if not exists idx_appointments_client on public.appointments(client_id);
create index if not exists idx_appointments_procedure on public.appointments(procedure_id);
create index if not exists idx_expenses_date on public.expenses(expense_date);
create index if not exists idx_clients_name on public.clients(name);
create index if not exists idx_procedures_name_active on public.procedures(name, active);

-- Para usar com SUPABASE_SERVICE_ROLE_KEY no backend, RLS pode permanecer desativado.
-- Se quiser RLS no futuro, habilite e crie policies explicitas.
